import { spawn } from "node:child_process";
import { randomBytes } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { createServer, request as httpRequest } from "node:http";
import { createServer as createNetServer } from "node:net";
import { homedir, hostname } from "node:os";
import { join } from "node:path";
import { EntityBackedPostgres } from "./lib/entity-backed-postgres.mjs";
import {
  EntityLease,
  EntitySnapshotStore,
  EntityStoreClient,
} from "./lib/entity-store.mjs";
import { EntityRuntimeStore } from "./lib/entity-runtime.mjs";

const serviceName = process.env.OMNIRA_SERVICE_NAME || "paperclip";
const publicHost =
  process.env.PAPERCLIP_PUBLIC_HOST ||
  `${serviceName}-k4u67azzg5.app.omnira.dev`;
const publicUrl =
  process.env.PAPERCLIP_AUTH_PUBLIC_BASE_URL || `https://${publicHost}`;
const instanceId = process.env.PAPERCLIP_INSTANCE_ID || "default";
const paperclipHome =
  process.env.PAPERCLIP_HOME || join(homedir(), ".paperclip-omnira");
const configPath = join(
  paperclipHome,
  "instances",
  instanceId,
  "config.json",
);
const cli = join(process.cwd(), "node_modules", "paperclipai", "dist", "index.js");

mkdirSync(paperclipHome, { recursive: true });

function paperclipArgs() {
  return existsSync(configPath)
    ? [cli, "run"]
    : [cli, "onboard", "--yes", "--data-dir", paperclipHome];
}

function paperclipEnvironment({ port, databaseUrl }) {
  return {
    ...process.env,
    HOST: "127.0.0.1",
    PORT: String(port),
    DATABASE_URL: databaseUrl,
    PAPERCLIP_HOME: paperclipHome,
    PAPERCLIP_INSTANCE_ID: instanceId,
    PAPERCLIP_BIND: "custom",
    PAPERCLIP_BIND_HOST: "127.0.0.1",
    PAPERCLIP_DEPLOYMENT_MODE: "authenticated",
    PAPERCLIP_DEPLOYMENT_EXPOSURE:
      process.env.PAPERCLIP_DEPLOYMENT_EXPOSURE || "private",
    PAPERCLIP_AUTH_BASE_URL_MODE: "explicit",
    PAPERCLIP_AUTH_PUBLIC_BASE_URL: publicUrl,
    PAPERCLIP_ALLOWED_HOSTNAMES: [
      publicHost,
      "127.0.0.1",
      "localhost",
    ].join(","),
    BETTER_AUTH_TRUSTED_ORIGINS: publicUrl,
    PAPERCLIP_MIGRATION_AUTO_APPLY: "true",
    PAPERCLIP_DB_BACKUP_ENABLED: "false",
    PAPERCLIP_OPEN_ON_LISTEN: "false",
    PAPERCLIP_NO_BROWSER: "1",
    PAPERCLIP_TELEMETRY_DISABLED: "1",
    DO_NOT_TRACK: "1",
  };
}

function spawnPaperclip(env) {
  return spawn(process.execPath, paperclipArgs(), {
    env,
    stdio: "inherit",
  });
}

function ensureOmniraConfig({ appPort, databaseUrl }) {
  const instanceRoot = join(paperclipHome, "instances", instanceId);
  const envPath = join(instanceRoot, ".env");
  const secretsPath = join(instanceRoot, "secrets", "master.key");
  const storagePath = join(instanceRoot, "data", "storage");
  const backupPath = join(instanceRoot, "data", "backups");
  const logPath = join(instanceRoot, "logs");
  mkdirSync(join(instanceRoot, "secrets"), { recursive: true });
  mkdirSync(storagePath, { recursive: true });

  if (!existsSync(envPath)) {
    writeFileSync(
      envPath,
      `# Paperclip environment variables\n# Generated by paperclip-omnira\nPAPERCLIP_AGENT_JWT_SECRET=${randomBytes(32).toString("hex")}\n`,
      { mode: 0o600 },
    );
  } else if (!/^PAPERCLIP_AGENT_JWT_SECRET=/m.test(readFileSync(envPath, "utf8"))) {
    writeFileSync(
      envPath,
      `${readFileSync(envPath, "utf8").trimEnd()}\nPAPERCLIP_AGENT_JWT_SECRET=${randomBytes(32).toString("hex")}\n`,
      { mode: 0o600 },
    );
  }
  if (!existsSync(secretsPath)) {
    writeFileSync(secretsPath, randomBytes(32).toString("base64"), { mode: 0o600 });
  }

  let existing = {};
  if (existsSync(configPath)) {
    try {
      existing = JSON.parse(readFileSync(configPath, "utf8"));
    } catch {
      existing = {};
    }
  }
  const exposure = process.env.PAPERCLIP_DEPLOYMENT_EXPOSURE || "private";
  const config = {
    ...existing,
    $meta: {
      version: 1,
      updatedAt: new Date().toISOString(),
      source: existing.$meta?.source || "onboard",
    },
    database: {
      ...existing.database,
      mode: "postgres",
      connectionString: databaseUrl,
      embeddedPostgresDataDir: join(instanceRoot, "db"),
      embeddedPostgresPort: 54329,
      backup: {
        enabled: false,
        intervalMinutes: 60,
        retentionDays: 1,
        dir: backupPath,
      },
    },
    logging: {
      mode: existing.logging?.mode || "file",
      logDir: logPath,
    },
    server: {
      ...existing.server,
      deploymentMode: "authenticated",
      exposure,
      bind: "custom",
      customBindHost: "127.0.0.1",
      host: "127.0.0.1",
      port: appPort,
      allowedHostnames: [publicHost, "127.0.0.1", "localhost"],
      serveUi: true,
    },
    auth: {
      ...existing.auth,
      baseUrlMode: "explicit",
      publicBaseUrl: publicUrl,
      disableSignUp: existing.auth?.disableSignUp ?? false,
    },
    telemetry: { enabled: false },
    storage: {
      ...existing.storage,
      provider: existing.storage?.provider || "local_disk",
      localDisk: { baseDir: storagePath },
      s3: {
        ...existing.storage?.s3,
        bucket: "paperclip",
        region: "us-east-1",
        prefix: "",
        forcePathStyle: false,
      },
    },
    secrets: {
      provider: "local_encrypted",
      strictMode: true,
      localEncrypted: { keyFilePath: secretsPath },
    },
  };
  writeFileSync(configPath, `${JSON.stringify(config, null, 2)}\n`, { mode: 0o600 });
}

async function findFreePort(excluded = new Set()) {
  for (;;) {
    const port = await new Promise((resolve, reject) => {
      const server = createNetServer();
      server.once("error", reject);
      server.listen(0, "127.0.0.1", () => {
        const address = server.address();
        const selected = typeof address === "object" && address ? address.port : 0;
        server.close((error) => (error ? reject(error) : resolve(selected)));
      });
    });
    if (!excluded.has(port)) return port;
  }
}

async function waitForHealth(port, child, timeoutMs = 120_000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (child.exitCode !== null) {
      throw new Error(`Paperclip exited before becoming healthy (code ${child.exitCode})`);
    }
    try {
      const response = await fetch(`http://127.0.0.1:${port}/api/health`);
      if (response.ok) return;
    } catch {
      // Startup can take a while while Paperclip migrates a restored database.
    }
    await new Promise((resolve) => setTimeout(resolve, 500));
  }
  throw new Error("Paperclip did not become healthy within 120 seconds");
}

async function terminateChild(child, timeoutMs = 5_000) {
  if (!child || child.exitCode !== null) return;
  child.kill("SIGTERM");
  await Promise.race([
    new Promise((resolve) => child.once("exit", resolve)),
    new Promise((resolve) => setTimeout(resolve, timeoutMs)),
  ]);
  if (child.exitCode === null) {
    child.kill("SIGKILL");
    await new Promise((resolve) => child.once("exit", resolve));
  }
}

function writeJson(response, statusCode, value) {
  response.writeHead(statusCode, {
    "Cache-Control": "no-store",
    "Content-Type": "application/json; charset=utf-8",
  });
  response.end(`${JSON.stringify(value, null, 2)}\n`);
}

function renderWaitingPage(status) {
  const title = status.mode === "error" ? "Storage setup needed" : "Standby replica";
  const detail = status.error ||
    "This device is waiting for the active Paperclip lease. It will promote automatically if the leader disappears.";
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>Paperclip · ${title}</title><style>
body{margin:0;min-height:100vh;display:grid;place-items:center;background:#f6f4ee;color:#23221f;font:16px/1.5 ui-sans-serif,system-ui,sans-serif}
main{max-width:680px;margin:24px;padding:32px;border:1px solid #d8d3c8;border-radius:18px;background:#fff;box-shadow:0 18px 60px #352f2420}
.eyebrow{color:#756c5d;font-size:12px;font-weight:700;letter-spacing:.12em;text-transform:uppercase}h1{font-size:34px;line-height:1.1;margin:.5rem 0 1rem}code{background:#f1eee7;padding:.15rem .35rem;border-radius:5px}a{color:#6a4d25}
</style></head><body><main><div class="eyebrow">Paperclip on Omnira Entity Service</div><h1>${title}</h1><p>${detail}</p><p>Machine-readable proof: <a href="/_omnira/storage"><code>/_omnira/storage</code></a></p></main></body></html>`;
}

async function runLegacyLocalMode() {
  const port = Number(process.env.PORT || 8080);
  const env = paperclipEnvironment({ port, databaseUrl: process.env.DATABASE_URL });
  delete env.DATABASE_URL;
  const child = spawnPaperclip(env);
  for (const signal of ["SIGINT", "SIGTERM"]) {
    process.on(signal, () => child.kill(signal));
  }
  child.on("exit", (code, signal) => {
    if (signal) process.kill(process.pid, signal);
    process.exit(code ?? 1);
  });
}

async function runEntityMode() {
  const publicPort = Number(process.env.PORT || 8080);
  const status = {
    ok: false,
    storageBackend: "omnira-entity-blockstore",
    entityServiceUrl:
      process.env.OMNIRA_ENTITY_URL ||
      "https://entityservice-k4u67azzg5.app.omnira.dev",
    namespace: process.env.OMNIRA_ENTITY_NAMESPACE || "paperclip",
    instanceId,
    mode: "starting",
    holder: process.env.BAD_DEVICE_ENTITY_ID || `${hostname()}:${process.pid}`,
    publicUrl,
    backupIntervalSeconds: Math.max(
      15,
      Number(process.env.OMNIRA_ENTITY_BACKUP_INTERVAL_SECONDS || 60),
    ),
    leaseTtlSeconds: Math.max(
      20,
      Number(process.env.OMNIRA_ENTITY_LEASE_TTL_SECONDS || 45),
    ),
    lastDatabaseSnapshot: null,
    lastRuntimeSnapshot: null,
    lastBackupReason: null,
    lastBackupError: null,
    updatedAt: new Date().toISOString(),
  };

  let upstreamPort = null;
  let child = null;
  let postgres = null;
  let lease = null;
  let runtimeStore = null;
  let backupTimer = null;
  let renewTimer = null;
  let standbyTimer = null;
  let backupPromise = null;
  let transitionRunning = false;
  let expectedChildExit = false;
  let stopping = false;

  const updateStatus = (changes) => {
    Object.assign(status, changes, { updatedAt: new Date().toISOString() });
  };

  const proxyServer = createServer((request, response) => {
    if (request.url === "/_omnira/storage" || request.url?.startsWith("/_omnira/storage?")) {
      writeJson(response, status.ok ? 200 : 503, status);
      return;
    }
    if (!upstreamPort) {
      if ((request.headers.accept || "").includes("text/html")) {
        response.writeHead(503, {
          "Cache-Control": "no-store",
          "Content-Type": "text/html; charset=utf-8",
        });
        response.end(renderWaitingPage(status));
      } else {
        writeJson(response, 503, { error: status.error || "Paperclip is not the active leader" });
      }
      return;
    }

    const upstream = httpRequest(
      {
        host: "127.0.0.1",
        port: upstreamPort,
        method: request.method,
        path: request.url,
        headers: request.headers,
      },
      (upstreamResponse) => {
        response.writeHead(upstreamResponse.statusCode || 502, upstreamResponse.headers);
        upstreamResponse.pipe(response);
      },
    );
    upstream.on("error", (error) => {
      if (!response.headersSent) writeJson(response, 502, { error: error.message });
      else response.destroy(error);
    });
    request.pipe(upstream);
  });

  proxyServer.on("upgrade", (request, socket, head) => {
    if (!upstreamPort) {
      socket.destroy();
      return;
    }
    const upstream = httpRequest({
      host: "127.0.0.1",
      port: upstreamPort,
      method: request.method,
      path: request.url,
      headers: request.headers,
    });
    upstream.on("upgrade", (response, upstreamSocket, upstreamHead) => {
      const headers = Object.entries(response.headers)
        .flatMap(([name, value]) =>
          Array.isArray(value) ? value.map((item) => `${name}: ${item}`) : [`${name}: ${value}`],
        )
        .join("\r\n");
      socket.write(`HTTP/1.1 ${response.statusCode} ${response.statusMessage}\r\n${headers}\r\n\r\n`);
      if (head.length) upstreamSocket.write(head);
      if (upstreamHead.length) socket.write(upstreamHead);
      upstreamSocket.pipe(socket).pipe(upstreamSocket);
    });
    upstream.on("error", () => socket.destroy());
    upstream.end();
  });

  await new Promise((resolve, reject) => {
    proxyServer.once("error", reject);
    proxyServer.listen(publicPort, "0.0.0.0", resolve);
  });
  console.log(`[paperclip-omnira] public proxy listening on :${publicPort}`);

  const apiKey = process.env.OMNIRA_ENTITY_API_KEY;
  const ownerEntityId = process.env.OMNIRA_ENTITY_OWNER_ID;
  if (!apiKey || !ownerEntityId) {
    updateStatus({
      mode: "error",
      error:
        "OMNIRA_ENTITY_API_KEY and OMNIRA_ENTITY_OWNER_ID are required for Entity Service storage",
    });
    return;
  }

  const client = new EntityStoreClient({
    baseUrl: status.entityServiceUrl,
    apiKey,
    namespace: status.namespace,
    ownerEntityId,
  });
  const keyPrefix = `paperclip/instances/${instanceId}`;
  lease = new EntityLease({
    client,
    key: `${keyPrefix}/leader.json`,
    holder: status.holder,
    ttlMs: status.leaseTtlSeconds * 1000,
  });
  const databaseSnapshots = new EntitySnapshotStore({
    client,
    keyPrefix: `${keyPrefix}/database`,
  });
  const runtimeSnapshots = new EntitySnapshotStore({
    client,
    keyPrefix: `${keyPrefix}/runtime`,
  });
  runtimeStore = new EntityRuntimeStore({
    paperclipHome,
    instanceId,
    snapshotStore: runtimeSnapshots,
  });

  const performBackup = async (reason) => {
    if (!postgres) return null;
    if (backupPromise) return backupPromise;
    updateStatus({ backupState: "running", lastBackupReason: reason, lastBackupError: null });
    backupPromise = (async () => {
      const databaseSnapshot = await postgres.backup();
      const runtimeSnapshot = await runtimeStore.backup();
      updateStatus({
        backupState: "idle",
        lastDatabaseSnapshot: databaseSnapshot,
        lastRuntimeSnapshot: runtimeSnapshot,
        lastBackupAt: new Date().toISOString(),
      });
      return databaseSnapshot;
    })();
    try {
      return await backupPromise;
    } catch (error) {
      updateStatus({ backupState: "error", lastBackupError: error.message });
      throw error;
    } finally {
      backupPromise = null;
    }
  };

  const clearLeaderTimers = () => {
    if (backupTimer) clearInterval(backupTimer);
    if (renewTimer) clearInterval(renewTimer);
    backupTimer = null;
    renewTimer = null;
  };

  const stopLeader = async ({ finalBackup = false, release = false } = {}) => {
    clearLeaderTimers();
    upstreamPort = null;
    if (finalBackup && postgres) {
      try {
        await performBackup("graceful-shutdown");
      } catch (error) {
        console.error(`[paperclip-omnira] final backup failed: ${error.message}`);
      }
    }
    if (child && child.exitCode === null) {
      expectedChildExit = true;
      await terminateChild(child);
    }
    child = null;
    if (postgres) {
      await postgres.stop();
      postgres = null;
    }
    if (release && lease) {
      try {
        await lease.release();
      } catch (error) {
        console.error(`[paperclip-omnira] lease release failed: ${error.message}`);
      }
    }
  };

  const enterStandby = async (reason) => {
    if (stopping) return;
    updateStatus({ ok: false, mode: "standby", standbyReason: reason, leaseExpiresAt: null });
    clearLeaderTimers();
    upstreamPort = null;
    if (!standbyTimer) {
      standbyTimer = setInterval(() => void tryLeadership(), 5_000);
    }
  };

  const becomeLeader = async () => {
    updateStatus({
      ok: false,
      mode: "restoring",
      error: null,
      standbyReason: null,
      leaseExpiresAt: lease.expiresAt,
    });
    const restoredRuntime = await runtimeStore.restoreLatest();
    updateStatus({ restoredRuntimeSnapshot: restoredRuntime });

    const usedPorts = new Set([publicPort]);
    const databasePort = Number(process.env.PAPERCLIP_POSTGRES_PORT) ||
      (await findFreePort(usedPorts));
    usedPorts.add(databasePort);
    const appPort = Number(process.env.PAPERCLIP_INTERNAL_PORT) ||
      (await findFreePort(usedPorts));

    postgres = new EntityBackedPostgres({
      dataDir: join(paperclipHome, ".entity-postgres", instanceId),
      port: databasePort,
      snapshotStore: databaseSnapshots,
      onLog: (message) => {
        if (process.env.OMNIRA_ENTITY_POSTGRES_LOGS === "1") console.log(message);
      },
      onError: (message) => console.error(message),
    });
    const databaseUrl = await postgres.start();
    ensureOmniraConfig({ appPort, databaseUrl });
    updateStatus({
      mode: "starting-paperclip",
      restoredDatabaseSnapshot: postgres.lastSnapshot,
    });

    child = spawnPaperclip(paperclipEnvironment({ port: appPort, databaseUrl }));
    expectedChildExit = false;
    child.once("exit", (code, signal) => {
      if (expectedChildExit || stopping) return;
      console.error(
        `[paperclip-omnira] Paperclip exited unexpectedly (${signal || code})`,
      );
      updateStatus({ ok: false, mode: "error", error: "Paperclip exited unexpectedly" });
      void stopLeader({ finalBackup: true, release: true })
        .then(() => enterStandby("Paperclip process exited"))
        .catch((error) => updateStatus({ mode: "error", error: error.message }));
    });
    await waitForHealth(appPort, child);
    upstreamPort = appPort;
    updateStatus({
      ok: true,
      mode: "leader",
      leaseExpiresAt: lease.expiresAt,
      paperclipHealth: "ok",
      databaseEngine: "embedded-postgres",
      durableStore: "Omnira Entity Service BlockStore",
    });
    console.log("[paperclip-omnira] leader is healthy; Entity Service persistence active");

    await performBackup("leader-startup");
    backupTimer = setInterval(() => {
      void performBackup("interval").catch((error) =>
        console.error(`[paperclip-omnira] interval backup failed: ${error.message}`),
      );
    }, status.backupIntervalSeconds * 1000);
    renewTimer = setInterval(() => {
      void lease.renew()
        .then(async (renewed) => {
          if (renewed) {
            updateStatus({ leaseExpiresAt: lease.expiresAt });
            return;
          }
          updateStatus({ ok: false, mode: "demoting", error: "Entity lease was lost" });
          await stopLeader({ finalBackup: false, release: false });
          await enterStandby("Entity lease was lost");
        })
        .catch(async (error) => {
          updateStatus({ leaseRenewalError: error.message });
          console.error(`[paperclip-omnira] lease renewal failed: ${error.message}`);
          updateStatus({ ok: false, mode: "demoting", error: "Entity lease renewal failed" });
          await stopLeader({ finalBackup: false, release: false });
          await enterStandby("Entity lease renewal failed");
        });
    }, Math.floor((status.leaseTtlSeconds * 1000) / 3));
  };

  async function tryLeadership() {
    if (transitionRunning || stopping || status.mode === "leader") return;
    transitionRunning = true;
    try {
      const acquired = await lease.acquire();
      if (!acquired) {
        const current = await client.getJsonOptional(`${keyPrefix}/leader.json`);
        updateStatus({
          ok: false,
          mode: "standby",
          activeHolder: current?.value?.holder ?? null,
          leaseExpiresAt: current?.value?.expiresAt ?? null,
          error: null,
        });
        return;
      }
      if (standbyTimer) clearInterval(standbyTimer);
      standbyTimer = null;
      await becomeLeader();
    } catch (error) {
      console.error(`[paperclip-omnira] leadership transition failed: ${error.stack || error}`);
      updateStatus({ ok: false, mode: "error", error: error.message });
      await stopLeader({ finalBackup: false, release: true }).catch(() => {});
      if (!standbyTimer && !stopping) {
        standbyTimer = setInterval(() => void tryLeadership(), 10_000);
      }
    } finally {
      transitionRunning = false;
    }
  }

  const shutdown = async (signal) => {
    if (stopping) return;
    stopping = true;
    if (standbyTimer) clearInterval(standbyTimer);
    updateStatus({ ok: false, mode: "stopping", shutdownSignal: signal });
    await stopLeader({ finalBackup: true, release: true });
    proxyServer.closeIdleConnections?.();
    const closed = new Promise((resolve) => proxyServer.close(resolve));
    await Promise.race([closed, new Promise((resolve) => setTimeout(resolve, 2_000))]);
    proxyServer.closeAllConnections?.();
    process.exit(0);
  };

  for (const signal of ["SIGINT", "SIGTERM"]) {
    process.on(signal, () => void shutdown(signal));
  }

  await tryLeadership();
  if (status.mode !== "leader" && !standbyTimer) {
    await enterStandby("Another Omnira device holds the Entity lease");
  }
}

const storageBackend = process.env.PAPERCLIP_STORAGE_BACKEND || "omnira-entity";
if (storageBackend === "local") {
  await runLegacyLocalMode();
} else if (storageBackend === "omnira-entity") {
  await runEntityMode();
} else {
  throw new Error(`Unsupported PAPERCLIP_STORAGE_BACKEND: ${storageBackend}`);
}
